name: github_repository_search
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  collection: ^1.16.0

  cupertino_icons: ^1.0.2
  device_info_plus: ^7.0.1
  device_preview: ^1.1.0
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  dynamic_color: ^1.5.4
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^5.1.0
  hooks_riverpod: ^2.0.2
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  lottie: ^1.4.3
  retrofit: ^3.3.1
  riverpod_annotation: ^1.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  slang: ^3.1.0
  slang_flutter: ^3.1.0
  substring_highlight: ^1.0.33
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  go_router_builder: ^1.0.14
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.1
  pedantic_mono: ^1.20.0
  retrofit_generator: ^4.2.0
  riverpod_generator: ^1.0.4
  slang_build_runner: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
